apiVersion: apps/v1
kind: Deployment
metadata:
  name: ArgoAwsApp-deployment
  labels:
    app: ArgoAwsApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ArgoAwsApp
  template:
    metadata:
      name: ArgoAwsApp
      labels:
        app: ArgoAwsApp
    spec:
      containers:
        - name: ArgoAwsApp
          image: 897729139176.dkr.ecr.ap-northeast-2.amazonaws.com/eks/eks1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe: # 추가
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe: # 추가
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
          resources: # 추가
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          restartPolicy: Always