apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-aws-data-pv
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: argo-aws-data
  nfs:
    server: 123.123.???.???
    path: /tmp/argo-aws-data-pv
    
    ## AccessMode
    #ReadWriteOnce (RWO): 읽기/쓰기 권한이 있는 단일 파드에만 마운트 가능
    #ReadOnlyMany (ROX): 여러 파드에서 읽기 전용으로 마운트 가능
    #ReadWriteMany (RWX): 여러 파드에서 읽기/쓰기 권한을 가지고 마운트 가능
    
    ## persistentVolumeReclaimPolicy PV, PVC 연결 정책
    #Retain: PVC 삭제 -> PV 데이터 유지
    #Delete: PVC 삭제 -> PV 삭제, 외부 스토리지 데이터 삭제
    
    ## storageClassName PVC와 연결점