apiVersion: v1
kind: Service
metadata:
  name: argo-aws-app-service
spec:
  selector:
    app: argo-aws-app # Deployment 라벨과 일치해야 함
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # 컨테이너포트
  type: LoadBalancer
  