apiVersion: v1
kind: Service
metadata:
  name: argo-aws-data-service
spec:
  selector:
    app: argo-aws-data # Deployment 라벨과 일치해야 함
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 # 컨테이너포트
  type: ClusterIP
  