#MyDataSecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mydata-basic-auth
type: Opaque
stringData:
  username: "root"
  password: "k8s12345"

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...

#kubernetes.io/basic-auth는 일반적으로 HTTP Basic Auth에 사용